$source = "newfaciltiespics"
$dest = "public/assets/facilities"
Ensure-Directory $dest

Copy-Item "$source/Accounting facilities mac..png" "$dest/accounting-mac.png"
Copy-Item "$source/Energy Facilities Mac..png" "$dest/energy-mac.png"
Copy-Item "$source/Energy Facilities Mobile.png" "$dest/energy-mobile.png"
Copy-Item "$source/F&B facilities mac..png" "$dest/fnb-mac.png"
Copy-Item "$source/F&B Facilities Mobile..png" "$dest/fnb-mobile.png"
Copy-Item "$source/GatePass facilities mac..png" "$dest/gatepass-mac.png"
Copy-Item "$source/Gate pass facilities mobile..png" "$dest/gatepass-mobile.png"
Copy-Item "$source/Incident Management Facilities Mac.png" "$dest/incident-mac.png"
Copy-Item "$source/Incident Management Facilities Mobile.png" "$dest/incident-mobile.png"
Copy-Item "$source/Lease Management Facilities, MAC.png" "$dest/lease-mac.png"
Copy-Item "$source/M safe. Facilities mac..png" "$dest/msafe-mac.png"
Copy-Item "$source/MSafe Facilities Mobile.png" "$dest/msafe-mobile.png"
Copy-Item "$source/Mailroom facilities mac.png" "$dest/mailroom-mac.png"
Copy-Item "$source/Mailroom facilities mobile.png" "$dest/mailroom-mobile.png"
Copy-Item "$source/Material ManagementFacilities Mac.png" "$dest/material-mac.png"
Copy-Item "$source/Meter reading facilities mac..png" "$dest/meter-mac.png"
Copy-Item "$source/Meter reading facilities mobile..png" "$dest/meter-mobile.png"
Copy-Item "$source/Parking Facilities  mac..png" "$dest/parking-mac.png"
Copy-Item "$source/Parking Facilities Mobile.png" "$dest/parking-mobile.png"
Copy-Item "$source/Procurement Facilities Mac.png" "$dest/procurement-mac.png"
Copy-Item "$source/Schedule and task , facilities mac.png" "$dest/schedule-mac.png"
Copy-Item "$source/Schedule and task, facilities mobile.png" "$dest/schedule-mobile.png"
Copy-Item "$source/Survey Facilities Mac..png" "$dest/survey-mac.png"
Copy-Item "$source/Survey Facilities Mobile.png" "$dest/survey-mobile.png"
Copy-Item "$source/Vendor management. Facilities mac..png" "$dest/vendor-mac.png"
Copy-Item "$source/Waste management, Facilities mac.png" "$dest/waste-mac.png"
Copy-Item "$source/Water Facilities Mac..png" "$dest/water-mac.png"
Copy-Item "$source/Water Facilities Mobile.png" "$dest/water-mobile.png"

Write-Host "Images copied successfully."
